title: Chris Simon # your name (or website title) here
logo: "/images/IMG_0317.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This is a Github project page dedicated to my Assoc Data Analyst Programme journey.
  <br><br>
  In this page, I will be featuring the Capstone projects that we have embarked on in Excel Dashboard, MS SQL Server, PowerBi and Python. 
  <br><br>
  <a href="https://chrisjsimon.github.io/capstones.github.io/">Mr Simon's Capstone Projects</a> 
  
theme: jekyll-theme-modernist
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
