title: Associate Data Analyst Programme Portfolio by Chris Simon # your name (or website title) here
logo: "/images/capstone_photo_resized.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This is a Github project page dedicated to my Assoc Data Analyst Programme journey.
  <br><br>
  In this page, I will be featuring the Capstone projects that we have embarked on using <strong>Excel Dashboard</strong>, <strong>MS SQL Server</strong>, <strong>PowerBi</strong> and <strong>Python</strong>. 
  <p>
  - <a href="code_academy_experience">My Code Academy experience</a><br>
  - <a href="helpful_resources">Helpful Resources</a><br>
  - <a href="#" id="linkModal">Get in touch with me</a>
  </p>
 <div id="modal" class="offmodal">
    <div class="modal-container">
       <header>
            <span class="close">
               <a href="#">X</a>
             </span>
         </header>
        <br>
         <div class="modal-body">
            <h2>Get in touch with me</h2>
            <p>Please fill up the form below if you'd like to get in touch with me.</p>
            
              <form action="https://formspree.io/f/mlearnqr" method="POST">
                  <label>
                    <strong>Your name:</strong><br>
                    <input type="text" name="name" style="width:90%;border: 2px solid gray; border-radius: 4px; padding:8px 10px;">
                   </label>
                <br>
                <label>
                    <strong>Your email:</strong><br>
                    <input type="email" name="_replyto" style="width:90%;border: 2px solid gray; border-radius: 4px; padding:8px 10px;">
                </label>
                <br>
                <label>
                   <strong>Your message:</strong><br>
                   <textarea name="message" rows="8" cols="50"  style="width:90%;border: 2px solid gray; border-radius: 4px; padding:8px 10px;"></textarea>
                </label>
                   <!-- your other form fields go here -->
                <br>
                  <button type="submit">Send</button>
               </form>
            </div> <!-- modal-body -->
        </div> <!--modal-container -->
    </div> <!-- modal -->

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
