title: Associate Data Analyst Programme Portfolio by Chris Simon # your name (or website title) here
logo: "/images/capstone_photo_resized.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This is a Github project page dedicated to my Assoc Data Analyst Programme journey.
  <br><br>
  In this page, I will be featuring the Capstone projects that we have embarked on using <strong>Excel Dashboard</strong>, <strong>MS SQL Server</strong>, <strong>PowerBi</strong> and <strong>Python</strong>. 
  <p>
  - <a href="code_academy_experience">My Code Academy experience</a><br>
  </p>
  <p>
  - <a href="helpful_resources">Helpful Resources</a><br>
  </p>
 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
